{{- if .Values.global.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: discovery-operator-allow-webhook
  namespace: '{{ .Values.global.namespace }}'
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          policy-group.network.openshift.io/host-network: ''
    ports:
    - port: 9443
      protocol: TCP
  podSelector:
    matchLabels:
      app: discovery-operator
  policyTypes:
  - Ingress
{{- end }}
