# Do NOT set agentInstallNamespace - breaks ClusterRoleBinding subject namespaces.
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: cert-manager-addon
  namespace: {{ .Values.global.namespace }}
spec:
  customizedVariables:
    - name: certManagerCrdsUrl
      value: "https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.crds.yaml"
