global:
  deployOnOCP: true
  namespace: default
  olmVersion: v0
  pullSecret: null
  pullPolicy: IfNotPresent
  templateOverrides: {}
  networkPolicies:
    enabled: true
  imageOverrides:
    # Red Hat supported images (default). For community images, use
    # image-overrides-configmap annotation. See docs/override-images.md
    cert_manager_controller: "registry.redhat.io/cert-manager/cert-manager-controller-rhel9:v1.14.4"
    cert_manager_webhook: "registry.redhat.io/cert-manager/cert-manager-webhook-rhel9:v1.14.4"
    cert_manager_cainjector: "registry.redhat.io/cert-manager/cert-manager-cainjector-rhel9:v1.14.4"
    cert_manager_kubectl: "registry.redhat.io/openshift4/ose-cli:v4.17"
hubconfig:
  nodeSelector: null
  tolerations: []
  ocpVersion: 4.12.0
org: open-cluster-management
