# Build the backplane-operator binary
FROM registry.ci.openshift.org/stolostron/builder:go1.22-linux AS builder

WORKDIR /workspace

COPY api/ api/
COPY test/function_tests/ test/function_tests/
COPY go.mod go.mod
COPY go.sum go.sum

RUN go install github.com/onsi/ginkgo/v2/ginkgo@latest &&\
ginkgo build test/function_tests/backplane_operator_install_test

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

ENV KUBECONFIG "/opt/.kube/config"
ENV RESOURCE_DIR "resources"

USER root
WORKDIR /test

COPY --from=builder /workspace/test/function_tests/backplane_operator_install_test/backplane_operator_install_test.test backplane_operator_install_test/backplane_operator_install_test.test
COPY --from=builder /workspace/test/function_tests/resources/ resources/

CMD ["/test/backplane_operator_install_test/backplane_operator_install_test.test" , "-ginkgo.v"]
