

.PHONY: subscriptions

##@ Dev. targets

subscriptions: ## Applies upstream community subscriptions (Hive, Cluster-manager)
	oc create ns backplane-operator-system --dry-run=client -o yaml | oc apply -f -
	oc apply -k hack/subscriptions

add-images: ## Retrieves latest manifest and injects image definitions directly into the deployment template
	pip3 install -r ./hack/bundle-automation/requirements.txt
	python3 ./hack/scripts/dev-update-image-references.py

add-images-local:  ## Generates a local image manifest. Source this file to define necessary environment variables to run the operator locally
	pip3 install -r ./hack/bundle-automation/requirements.txt
	python3 ./hack/scripts/dev-update-image-references.py --local

upstream-install: ## Installs the upstream Backplane Operator by deploying a CatalogSource and Subscription
	bash ./hack/scripts/upstream-install.sh

lint-operator-bundles: ## Lints the operator bundles
	pip install -r hack/bundle-automation/requirements.txt
	python ./hack/bundle-automation/generate-bundles.py --lint

regenerate-operator-bundles: ## Regenerates the operator bundles
	pip install -r hack/bundle-automation/requirements.txt
	python ./hack/bundle-automation/generate-bundles.py --destination pkg/templates/

regenerate-charts: ## Regenerates the charts 
	pip install -r hack/bundle-automation/chart-requirements.txt
	python ./hack/bundle-automation/generate-charts.py --destination pkg/templates/

catalog-deploy: ## Deploys backplane operator via subscription
	IMG="${CATALOG_IMG}" yq eval -i '.spec.image = env(IMG)' hack/catalog/catalogsource.yaml
	oc create ns backplane-operator-system --dry-run=client -o yaml | oc apply -f -
	oc apply -k hack/catalog

full-catalog-install: generate bundle bundle-build bundle-push catalog-build catalog-push catalog-deploy ## Generates all required files and deploys backplane operator via subscription
