global:
  deployOnOCP: true
  namespace: default
  olmVersion: v0
  pullSecret: null
  templateOverrides: {}
  networkPolicies:
    enabled: true
hubconfig:
  clusterIngressDomain: ''
  consoleURL: ''
  localClusterName: ''
org: open-cluster-management
