apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
  name: capa-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awscluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awscluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsclustercontrolleridentity
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsclustercontrolleridentity.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclustercontrolleridentities
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsclusterroleidentity
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsclusterroleidentity.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclusterroleidentities
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsclusterstaticidentity
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsclusterstaticidentity.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclusterstaticidentities
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsclustertemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsclustertemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclustertemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachine
  failurePolicy: Fail
  name: mutation.awsmachine.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmachines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsfargateprofile
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsfargateprofile.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsfargateprofiles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachinepool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsmachinepool.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmachinepools
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsmanagedmachinepool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsmanagedmachinepool.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmanagedmachinepools
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-rosamachinepool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.rosamachinepool.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - rosamachinepools
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-rosaroleconfig
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.rosaroleconfig.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - rosaroleconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-bootstrap-cluster-x-k8s-io-v1beta2-eksconfig
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.eksconfigs.bootstrap.cluster.x-k8s.io
  rules:
  - apiGroups:
    - bootstrap.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - eksconfig
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-bootstrap-cluster-x-k8s-io-v1beta2-eksconfigtemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.eksconfigtemplates.bootstrap.cluster.x-k8s.io
  rules:
  - apiGroups:
    - bootstrap.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - eksconfigtemplate
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-controlplane-cluster-x-k8s-io-v1beta2-awsmanagedcontrolplane
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmanagedcontrolplanes
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-controlplane-cluster-x-k8s-io-v1beta2-awsmanagedcontrolplanetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsmanagedcontrolplanetemplates.controlplane.cluster.x-k8s.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmanagedcontrolplanetemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ default "capa-system" .Values.global.namespace }}'
      path: /mutate-controlplane-cluster-x-k8s-io-v1beta2-rosacontrolplane
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.rosacontrolplanes.controlplane.cluster.x-k8s.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - rosacontrolplanes
  sideEffects: None
