global:
  deployOnOCP: true
  imageOverrides:
    discovery_operator: ''
  namespace: default
  olmVersion: v0
  pullSecret: null
  templateOverrides: {}
  networkPolicies:
    enabled: true
hubconfig:
  nodeSelector: null
  ocpVersion: 4.12.0
  probeConfig: null
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
