apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Values.org }}:{{ .Chart.Name }}:image-based-install-operator'
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.hive.openshift.io
  resources:
  - imageclusterinstalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.hive.openshift.io
  resources:
  - imageclusterinstalls/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.hive.openshift.io
  resources:
  - imageclusterinstalls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterimagesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts/finalizers
  verbs:
  - update
- apiGroups:
  - metal3.io
  resources:
  - dataimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
