apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: imageclusterinstalls.extensions.hive.openshift.io
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-extensions-hive-openshift-io-v1alpha1-imageclusterinstall
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: imageclusterinstalls.extensions.hive.openshift.io
  rules:
  - apiGroups:
    - extensions.hive.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - imageclusterinstalls
  sideEffects: None
