apiVersion: v1
kind: Service
metadata:
  labels:
    component: cluster-proxy-addon-user
  name: cluster-proxy-addon-user
  namespace: '{{ .Values.global.namespace }}'
spec:
  ports:
  - name: https
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    component: cluster-proxy-addon-user
    open-cluster-management.io/addon: cluster-proxy
  type: ClusterIP
