apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capoa-controlplane-manager-role
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - openshiftassistedconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclustersets/join
  verbs:
  - create
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  - machines
  - machines/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinepools
  verbs:
  - list
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - openshiftassistedcontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - openshiftassistedcontrolplanes/finalizers
  verbs:
  - update
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - openshiftassistedcontrolplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions.hive.openshift.io
  resources:
  - agentclusterinstalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.hive.openshift.io
  resources:
  - agentclusterinstalls/status
  verbs:
  - get
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  - clusterimagesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments/status
  verbs:
  - get
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - metal3machines
  - metal3machinetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
