apiVersion: v1
kind: Service
metadata:
  name: maestro-db
  namespace: maestro
spec:
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: maestro-db
