apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ .Values.org }}:{{ .Chart.Name }}:assisted-service'
  namespace: '{{ .Values.global.namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ .Values.org }}:{{ .Chart.Name }}:assisted-service'
subjects:
- kind: ServiceAccount
  name: assisted-service
  namespace: '{{ .Values.global.namespace }}'
