apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: ipam-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ipam-manager-role
subjects:
- kind: ServiceAccount
  name: ipam-manager
  namespace: '{{ default "capm3-system" .Values.global.namespace }}'
