apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ipam-webhook-service-cert
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: ipam-webhook-service
  namespace: '{{ default "capm3-system" .Values.global.namespace }}'
spec:
  ports:
  - port: 443
    targetPort: ipam-webhook
  selector:
    cluster.x-k8s.io/provider: infrastructure-metal3
