apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: ipam-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ipam-webhook-service
      namespace: '{{ default "capm3-system" .Values.global.namespace }}'
      path: /validate-ipam-metal3-io-v1alpha1-ipaddress
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.ipaddress.ipam.metal3.io
  rules:
  - apiGroups:
    - ipam.metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ipaddresses
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ipam-webhook-service
      namespace: '{{ default "capm3-system" .Values.global.namespace }}'
      path: /validate-ipam-metal3-io-v1alpha1-ipclaim
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.ipclaim.ipam.metal3.io
  rules:
  - apiGroups:
    - ipam.metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ipclaims
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ipam-webhook-service
      namespace: '{{ default "capm3-system" .Values.global.namespace }}'
      path: /validate-ipam-metal3-io-v1alpha1-ippool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.ippool.ipam.metal3.io
  rules:
  - apiGroups:
    - ipam.metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ippools
  sideEffects: None
