apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-proxy
  # ACM override: upstream uses  .Release.Namespace . Backplane rendering engine
  # injects namespace from MCE spec.targetNamespace via Go Values struct.
  namespace: '{{ .Values.global.namespace }}'
