apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  name: azureserviceoperator-search-mwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-search-azure-com-v1api20220901-searchservice
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20220901.searchservices.search.azure.com
  rules:
  - apiGroups:
    - search.azure.com
    apiVersions:
    - v1api20220901
    operations:
    - CREATE
    - UPDATE
    resources:
    - searchservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-search-azure-com-v1api20231101-searchservice
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20231101.searchservices.search.azure.com
  rules:
  - apiGroups:
    - search.azure.com
    apiVersions:
    - v1api20231101
    operations:
    - CREATE
    - UPDATE
    resources:
    - searchservices
  sideEffects: None
