apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  name: azureserviceoperator-containerservice-vwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20240901-maintenanceconfiguration
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20240901.maintenanceconfigurations.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20240901
    operations:
    - CREATE
    - UPDATE
    resources:
    - maintenanceconfigurations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20240901-managedcluster
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20240901.managedclusters.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20240901
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20240901-managedclustersagentpool
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20240901.managedclustersagentpools.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20240901
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedclustersagentpools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20240901-trustedaccessrolebinding
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20240901.trustedaccessrolebindings.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20240901
    operations:
    - CREATE
    - UPDATE
    resources:
    - trustedaccessrolebindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20250301-fleet
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20250301.fleets.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20250301
    operations:
    - CREATE
    - UPDATE
    resources:
    - fleets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20250301-fleetsautoupgradeprofile
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20250301.fleetsautoupgradeprofiles.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20250301
    operations:
    - CREATE
    - UPDATE
    resources:
    - fleetsautoupgradeprofiles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20250301-fleetsmember
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20250301.fleetsmembers.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20250301
    operations:
    - CREATE
    - UPDATE
    resources:
    - fleetsmembers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20250301-fleetsupdaterun
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20250301.fleetsupdateruns.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20250301
    operations:
    - CREATE
    - UPDATE
    resources:
    - fleetsupdateruns
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20250301-fleetsupdatestrategy
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20250301.fleetsupdatestrategies.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20250301
    operations:
    - CREATE
    - UPDATE
    resources:
    - fleetsupdatestrategies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20250801-maintenanceconfiguration
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20250801.maintenanceconfigurations.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20250801
    operations:
    - CREATE
    - UPDATE
    resources:
    - maintenanceconfigurations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20250801-managedcluster
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20250801.managedclusters.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20250801
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20250801-managedclustersagentpool
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20250801.managedclustersagentpools.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20250801
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedclustersagentpools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v1api20250801-trustedaccessrolebinding
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20250801.trustedaccessrolebindings.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v1api20250801
    operations:
    - CREATE
    - UPDATE
    resources:
    - trustedaccessrolebindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v20251002preview-maintenanceconfiguration
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v20251002preview.maintenanceconfigurations.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v20251002preview
    operations:
    - CREATE
    - UPDATE
    resources:
    - maintenanceconfigurations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v20251002preview-managedcluster
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v20251002preview.managedclusters.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v20251002preview
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v20251002preview-managedclustersagentpool
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v20251002preview.managedclustersagentpools.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v20251002preview
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedclustersagentpools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-containerservice-azure-com-v20251002preview-trustedaccessrolebinding
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v20251002preview.trustedaccessrolebindings.containerservice.azure.com
  rules:
  - apiGroups:
    - containerservice.azure.com
    apiVersions:
    - v20251002preview
    operations:
    - CREATE
    - UPDATE
    resources:
    - trustedaccessrolebindings
  sideEffects: None
