apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  name: azureserviceoperator-databasewatcher-mwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-databasewatcher-azure-com-v20241001preview-sharedprivatelink
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20241001preview.sharedprivatelinks.databasewatcher.azure.com
  rules:
  - apiGroups:
    - databasewatcher.azure.com
    apiVersions:
    - v20241001preview
    operations:
    - CREATE
    - UPDATE
    resources:
    - sharedprivatelinks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-databasewatcher-azure-com-v20241001preview-target
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20241001preview.targets.databasewatcher.azure.com
  rules:
  - apiGroups:
    - databasewatcher.azure.com
    apiVersions:
    - v20241001preview
    operations:
    - CREATE
    - UPDATE
    resources:
    - targets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-databasewatcher-azure-com-v20241001preview-watcher
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20241001preview.watchers.databasewatcher.azure.com
  rules:
  - apiGroups:
    - databasewatcher.azure.com
    apiVersions:
    - v20241001preview
    operations:
    - CREATE
    - UPDATE
    resources:
    - watchers
  sideEffects: None
