apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  name: azureserviceoperator-signalrservice-vwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-signalrservice-azure-com-v1api20211001-signalr
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20211001.signalrs.signalrservice.azure.com
  rules:
  - apiGroups:
    - signalrservice.azure.com
    apiVersions:
    - v1api20211001
    operations:
    - CREATE
    - UPDATE
    resources:
    - signalrs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-signalrservice-azure-com-v1api20240301-customcertificate
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20240301.customcertificates.signalrservice.azure.com
  rules:
  - apiGroups:
    - signalrservice.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - customcertificates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-signalrservice-azure-com-v1api20240301-customdomain
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20240301.customdomains.signalrservice.azure.com
  rules:
  - apiGroups:
    - signalrservice.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - customdomains
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-signalrservice-azure-com-v1api20240301-replica
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20240301.replicas.signalrservice.azure.com
  rules:
  - apiGroups:
    - signalrservice.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - replicas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-signalrservice-azure-com-v1api20240301-signalr
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20240301.signalrs.signalrservice.azure.com
  rules:
  - apiGroups:
    - signalrservice.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - signalrs
  sideEffects: None
