apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  name: azureserviceoperator-quota-mwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-quota-azure-com-v1api20250901-quota
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20250901.quotas.quota.azure.com
  rules:
  - apiGroups:
    - quota.azure.com
    apiVersions:
    - v1api20250901
    operations:
    - CREATE
    - UPDATE
    resources:
    - quotas
  sideEffects: None
