apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  name: azureserviceoperator-devices-vwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-devices-azure-com-v1api20210702-iothub
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20210702.iothubs.devices.azure.com
  rules:
  - apiGroups:
    - devices.azure.com
    apiVersions:
    - v1api20210702
    operations:
    - CREATE
    - UPDATE
    resources:
    - iothubs
  sideEffects: None
