apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  name: azureserviceoperator-subscription-mwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-subscription-azure-com-v1api20211001-alias
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20211001.aliases.subscription.azure.com
  rules:
  - apiGroups:
    - subscription.azure.com
    apiVersions:
    - v1api20211001
    operations:
    - CREATE
    - UPDATE
    resources:
    - aliases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-subscription-azure-com-v20211001-alias
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20211001.aliases.subscription.azure.com
  rules:
  - apiGroups:
    - subscription.azure.com
    apiVersions:
    - v20211001
    operations:
    - CREATE
    - UPDATE
    resources:
    - aliases
  sideEffects: None
