apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  name: azureserviceoperator-monitor-vwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /validate-monitor-azure-com-v1api20230403-account
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20230403.accounts.monitor.azure.com
  rules:
  - apiGroups:
    - monitor.azure.com
    apiVersions:
    - v1api20230403
    operations:
    - CREATE
    - UPDATE
    resources:
    - accounts
  sideEffects: None
