apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: capz-system/azureserviceoperator-serving-cert
  name: azureserviceoperator-operationalinsights-vwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-operationalinsights-azure-com-v1api20210601-workspace
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20210601.workspaces.operationalinsights.azure.com
  rules:
  - apiGroups:
    - operationalinsights.azure.com
    apiVersions:
    - v1api20210601
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-operationalinsights-azure-com-v20250701-workspace
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v20250701.workspaces.operationalinsights.azure.com
  rules:
  - apiGroups:
    - operationalinsights.azure.com
    apiVersions:
    - v20250701
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspaces
  sideEffects: None
