apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: capz-system/azureserviceoperator-serving-cert
  name: azureserviceoperator-containerregistry-vwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-containerregistry-azure-com-v1api20210901-registry
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20210901.registries.containerregistry.azure.com
  rules:
  - apiGroups:
    - containerregistry.azure.com
    apiVersions:
    - v1api20210901
    operations:
    - CREATE
    - UPDATE
    resources:
    - registries
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-containerregistry-azure-com-v1api20230701-registry
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20230701.registries.containerregistry.azure.com
  rules:
  - apiGroups:
    - containerregistry.azure.com
    apiVersions:
    - v1api20230701
    operations:
    - CREATE
    - UPDATE
    resources:
    - registries
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-containerregistry-azure-com-v1api20230701-registryreplication
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20230701.registryreplications.containerregistry.azure.com
  rules:
  - apiGroups:
    - containerregistry.azure.com
    apiVersions:
    - v1api20230701
    operations:
    - CREATE
    - UPDATE
    resources:
    - registryreplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-containerregistry-azure-com-v20251101-registrycacherule
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v20251101.registrycacherules.containerregistry.azure.com
  rules:
  - apiGroups:
    - containerregistry.azure.com
    apiVersions:
    - v20251101
    operations:
    - CREATE
    - UPDATE
    resources:
    - registrycacherules
  sideEffects: None
