apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: capz-system/azureserviceoperator-serving-cert
  name: azureserviceoperator-signalrservice-mwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-signalrservice-azure-com-v1api20211001-signalr
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20211001.signalrs.signalrservice.azure.com
  rules:
  - apiGroups:
    - signalrservice.azure.com
    apiVersions:
    - v1api20211001
    operations:
    - CREATE
    - UPDATE
    resources:
    - signalrs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-signalrservice-azure-com-v1api20240301-customcertificate
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20240301.customcertificates.signalrservice.azure.com
  rules:
  - apiGroups:
    - signalrservice.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - customcertificates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-signalrservice-azure-com-v1api20240301-customdomain
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20240301.customdomains.signalrservice.azure.com
  rules:
  - apiGroups:
    - signalrservice.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - customdomains
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-signalrservice-azure-com-v1api20240301-replica
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20240301.replicas.signalrservice.azure.com
  rules:
  - apiGroups:
    - signalrservice.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - replicas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-signalrservice-azure-com-v1api20240301-signalr
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20240301.signalrs.signalrservice.azure.com
  rules:
  - apiGroups:
    - signalrservice.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - signalrs
  sideEffects: None
