apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: capz-system/azureserviceoperator-serving-cert
  name: azureserviceoperator-redhatopenshift-vwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-redhatopenshift-azure-com-v1api20231122-openshiftcluster
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20231122.openshiftclusters.redhatopenshift.azure.com
  rules:
  - apiGroups:
    - redhatopenshift.azure.com
    apiVersions:
    - v1api20231122
    operations:
    - CREATE
    - UPDATE
    resources:
    - openshiftclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-redhatopenshift-azure-com-v1api20260630preview-hcpopenshiftcluster
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20260630preview.hcpopenshiftclusters.redhatopenshift.azure.com
  rules:
  - apiGroups:
    - redhatopenshift.azure.com
    apiVersions:
    - v1api20260630preview
    operations:
    - CREATE
    - UPDATE
    resources:
    - hcpopenshiftclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-redhatopenshift-azure-com-v1api20260630preview-hcpopenshiftclustersexternalauth
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20260630preview.hcpopenshiftclustersexternalauths.redhatopenshift.azure.com
  rules:
  - apiGroups:
    - redhatopenshift.azure.com
    apiVersions:
    - v1api20260630preview
    operations:
    - CREATE
    - UPDATE
    resources:
    - hcpopenshiftclustersexternalauths
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-redhatopenshift-azure-com-v1api20260630preview-hcpopenshiftclustersnodepool
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20260630preview.hcpopenshiftclustersnodepools.redhatopenshift.azure.com
  rules:
  - apiGroups:
    - redhatopenshift.azure.com
    apiVersions:
    - v1api20260630preview
    operations:
    - CREATE
    - UPDATE
    resources:
    - hcpopenshiftclustersnodepools
  sideEffects: None
