apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: capz-system/azureserviceoperator-serving-cert
  name: azureserviceoperator-entra-vwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-entra-azure-com-v1-securitygroup
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1.securitygroups.entra.azure.com
  rules:
  - apiGroups:
    - entra.azure.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - securitygroups
  sideEffects: None
