apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: capz-system/azureserviceoperator-serving-cert
  name: azureserviceoperator-app-mwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v1api20240301-authconfig
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20240301.authconfigs.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - authconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v1api20240301-containerapp
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20240301.containerapps.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - containerapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v1api20240301-job
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20240301.jobs.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v1api20240301-managedenvironment
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20240301.managedenvironments.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v1api20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedenvironments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v1api20250101-authconfig
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20250101.authconfigs.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v1api20250101
    operations:
    - CREATE
    - UPDATE
    resources:
    - authconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v1api20250101-containerapp
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20250101.containerapps.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v1api20250101
    operations:
    - CREATE
    - UPDATE
    resources:
    - containerapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v1api20250101-job
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20250101.jobs.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v1api20250101
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v1api20250101-managedenvironment
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20250101.managedenvironments.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v1api20250101
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedenvironments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v20240301-authconfig
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20240301.authconfigs.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - authconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v20240301-containerapp
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20240301.containerapps.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - containerapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v20240301-job
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20240301.jobs.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v20240301-managedenvironment
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20240301.managedenvironments.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v20240301
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedenvironments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v20250101-authconfig
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20250101.authconfigs.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v20250101
    operations:
    - CREATE
    - UPDATE
    resources:
    - authconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v20250101-containerapp
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20250101.containerapps.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v20250101
    operations:
    - CREATE
    - UPDATE
    resources:
    - containerapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v20250101-job
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20250101.jobs.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v20250101
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-app-azure-com-v20250101-managedenvironment
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20250101.managedenvironments.app.azure.com
  rules:
  - apiGroups:
    - app.azure.com
    apiVersions:
    - v20250101
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedenvironments
  sideEffects: None
