apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: capz-system/azureserviceoperator-serving-cert
  name: azureserviceoperator-alertsmanagement-vwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-alertsmanagement-azure-com-v1api20210401-smartdetectoralertrule
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20210401.smartdetectoralertrules.alertsmanagement.azure.com
  rules:
  - apiGroups:
    - alertsmanagement.azure.com
    apiVersions:
    - v1api20210401
    operations:
    - CREATE
    - UPDATE
    resources:
    - smartdetectoralertrules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-alertsmanagement-azure-com-v1api20230301-prometheusrulegroup
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v1api20230301.prometheusrulegroups.alertsmanagement.azure.com
  rules:
  - apiGroups:
    - alertsmanagement.azure.com
    apiVersions:
    - v1api20230301
    operations:
    - CREATE
    - UPDATE
    resources:
    - prometheusrulegroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-alertsmanagement-azure-com-v20210401-smartdetectoralertrule
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v20210401.smartdetectoralertrules.alertsmanagement.azure.com
  rules:
  - apiGroups:
    - alertsmanagement.azure.com
    apiVersions:
    - v20210401
    operations:
    - CREATE
    - UPDATE
    resources:
    - smartdetectoralertrules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /validate-alertsmanagement-azure-com-v20230301-prometheusrulegroup
  failurePolicy: Fail
  matchPolicy: Exact
  name: validate.v20230301.prometheusrulegroups.alertsmanagement.azure.com
  rules:
  - apiGroups:
    - alertsmanagement.azure.com
    apiVersions:
    - v20230301
    operations:
    - CREATE
    - UPDATE
    resources:
    - prometheusrulegroups
  sideEffects: None
