apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: capz-system/azureserviceoperator-serving-cert
  name: azureserviceoperator-appconfiguration-mwh
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-appconfiguration-azure-com-v1api20220501-configurationstore
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1api20220501.configurationstores.appconfiguration.azure.com
  rules:
  - apiGroups:
    - appconfiguration.azure.com
    apiVersions:
    - v1api20220501
    operations:
    - CREATE
    - UPDATE
    resources:
    - configurationstores
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-appconfiguration-azure-com-v20220501-configurationstore
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20220501.configurationstores.appconfiguration.azure.com
  rules:
  - apiGroups:
    - appconfiguration.azure.com
    apiVersions:
    - v20220501
    operations:
    - CREATE
    - UPDATE
    resources:
    - configurationstores
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-appconfiguration-azure-com-v20240601-configurationstore
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20240601.configurationstores.appconfiguration.azure.com
  rules:
  - apiGroups:
    - appconfiguration.azure.com
    apiVersions:
    - v20240601
    operations:
    - CREATE
    - UPDATE
    resources:
    - configurationstores
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-appconfiguration-azure-com-v20240601-keyvalue
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20240601.keyvalues.appconfiguration.azure.com
  rules:
  - apiGroups:
    - appconfiguration.azure.com
    apiVersions:
    - v20240601
    operations:
    - CREATE
    - UPDATE
    resources:
    - keyvalues
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-appconfiguration-azure-com-v20240601-replica
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20240601.replicas.appconfiguration.azure.com
  rules:
  - apiGroups:
    - appconfiguration.azure.com
    apiVersions:
    - v20240601
    operations:
    - CREATE
    - UPDATE
    resources:
    - replicas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: '{{ .Values.global.namespace }}'
      path: /mutate-appconfiguration-azure-com-v20240601-snapshot
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v20240601.snapshots.appconfiguration.azure.com
  rules:
  - apiGroups:
    - appconfiguration.azure.com
    apiVersions:
    - v20240601
    operations:
    - CREATE
    - UPDATE
    resources:
    - snapshots
  sideEffects: None
