global:
  deployOnOCP: true
  hubSize: Small
  imageOverrides:
    cluster_api_webhook_config_mce_29: ''
    ose_cluster_api_rhel9: ''
  namespace: default
  pullSecret: null
  templateOverrides: {}
hubconfig:
  nodeSelector: null
  ocpVersion: 4.12.0
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
